[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

# SPA fallback for Vite
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
